name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: SSH Remote Commands
    # You may pin to the exact commit or the version.
    # uses: appleboy/ssh-action@f9010ff7f1bbd7db1a0b4bab661437550cea20c0
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UBUNTU_IP }}
        username: ${{ secrets.UBUNTU_USERNAME }}
        key: ${{ secrets.UBUNTU_SSH_KEY}}
        port: ${{ secrets.PORT }}
        script: |
            cd test 
              git clone git@github.com:vedanshu-insonix/erp-django-backend.git
              git config --global user.name "vedanshu-insonix"
              
              
    
