name: Django CI/CD with Django, Postgres, Digitalocean

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_USER: doadmin
          POSTGRES_PASSWORD: AVNS_-Df0ctPeZMiFnZWBAYT
          POSTGRES_DB: defaultdb
          POSTGRES_PORT: 25060
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: doadmin
          POSTGRES_PASSWORD: AVNS_-Df0ctPeZMiFnZWBAYT
          POSTGRES_DB: defaultdb
          POSTGRES_PORT: 5432
        run: |
          python manage.py test

      - name: Push Main Branch into Production
        uses: vedanshu-insonix/erp-django-backend/action-branch-to-branch@main
        with:
          dest-branch: production-3
          source-branch: main
          commit-message: "Release production version"
        env:
          GITUB_TOCKEN: ${{ secrets.PERSONAL_ACCESS_TOCKEN }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Run a DOCTL Command
        run: |
          doctl apps update ${{ secrets.UBUNTU_SSH_KEY }} 
    
    
